SRC := kadai1-1.c \
			 kadai1-2.c \
			 kadai1-3.c \
			 kadai1-5.c \
			 kadai1-11.c \
			 kadai1-12.c \
			 kadai1-13.c \
			 kadai1-14.c \
			 kadai1-15.c \
			 kadai1-16.c \
			 kadai1-17.c \
			 kadai1-18.c \
			 kadai1-19.c \
			 kadai1-20.c

format:
	clang-format -i $(SRC)

clean:
	rm -f *.txt a.out

.PHONY: format clean
